<?xml version="1.0" encoding='utf-8'?>

<!--
	conjugation-en.xml - List of English conjugation templates.
	The templates were generated by SekouD using Unsupervised Learning,
	and follow the xml schema defined by Pierre Sarrazin in conjug_manager.

	Copyright (C) 2018 SekouD <https://github.com/SekouD>
	Copyright (C) 2010 Pierre Sarrazin <http://sarrazip.com/>

	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	You should have received a copy of the GNU General Public License
	along with this program; if not, write to the Free Software
	Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
	02110-1301, USA.
-->

<!DOCTYPE conjugation-en [
    <!ELEMENT conjugation-en (template)+>
    <!ATTLIST conjugation-en
      xmlns CDATA #FIXED ''>

    <!ELEMENT template (indicative,infinitive,imperative)>
    <!ATTLIST template
      xmlns CDATA #FIXED ''
      name NMTOKEN #REQUIRED>

    <!ELEMENT indicative (indicative-present,indicative-past-tense,
                          indicative-present-continuous,
                          indicative-present-perfect)>
    <!ATTLIST indicative
      xmlns CDATA #FIXED ''>

    <!ELEMENT infinitive (infinitive-present)>
    <!ATTLIST infinitive
      xmlns CDATA #FIXED ''>

    <!ELEMENT imperative (imperative-present)>
    <!ATTLIST imperative
      xmlns CDATA #FIXED ''>

    <!ELEMENT indicative-present (p)+>
    <!ATTLIST indicative-present
      xmlns CDATA #FIXED ''>

    <!ELEMENT indicative-past-tense (p)+>
    <!ATTLIST indicative-past-tense
      xmlns CDATA #FIXED ''>

    <!ELEMENT indicative-present-continuous (p)+>
    <!ATTLIST indicative-present-continuous
      xmlns CDATA #FIXED ''>

    <!ELEMENT indicative-present-perfect (p)+>
    <!ATTLIST indicative-present-perfect
      xmlns CDATA #FIXED ''>

    <!ELEMENT infinitive-present (p)>
    <!ATTLIST infinitive-present
      xmlns CDATA #FIXED ''>

    <!ELEMENT imperative-present (p)+>
    <!ATTLIST imperative-present
      xmlns CDATA #FIXED ''>

    <!ELEMENT p (i)>
    <!ATTLIST p
      xmlns CDATA #FIXED ''>

    <!ELEMENT i (#PCDATA)>
    <!ATTLIST i
      xmlns CDATA #FIXED ''>
]>

<conjugation-en>

<template name=":be">
	<indicative>
		<indicative-present>
			<p><i>am</i></p>
			<p><i>are</i></p>
			<p><i>is</i></p>
			<p><i>are</i></p>
			<p><i>are</i></p>
			<p><i>are</i></p>
		</indicative-present>
		<indicative-past-tense>
			<p><i>was</i></p>
			<p><i>were</i></p>
			<p><i>was</i></p>
			<p><i>were</i></p>
			<p><i>were</i></p>
			<p><i>were</i></p>
		</indicative-past-tense>
		<indicative-present-continuous>
			<p><i>being</i></p>
			<p><i>being</i></p>
			<p><i>being</i></p>
			<p><i>being</i></p>
			<p><i>being</i></p>
			<p><i>being</i></p>
		</indicative-present-continuous>
		<indicative-present-perfect>
			<p><i>been</i></p>
			<p><i>been</i></p>
			<p><i>been</i></p>
			<p><i>been</i></p>
			<p><i>been</i></p>
			<p><i>been</i></p>
		</indicative-present-perfect>
	</indicative>
	<infinitive>
		<infinitive-present>
			<p><i>be</i></p>
		</infinitive-present>
	</infinitive>
	<imperative>
		<imperative-present>
			<p><i>be</i></p>
			<p><i>be</i></p>
			<p><i>be</i></p>
		</imperative-present>
	</imperative>
</template>

<template name="beg:">
	<indicative>
		<indicative-present>
			<p><i></i></p>
			<p><i></i></p>
			<p><i>s</i></p>
			<p><i></i></p>
			<p><i></i></p>
			<p><i></i></p>
		</indicative-present>
		<indicative-past-tense>
			<p><i>ged</i></p>
			<p><i>ged</i></p>
			<p><i>ged</i></p>
			<p><i>ged</i></p>
			<p><i>ged</i></p>
			<p><i>ged</i></p>
		</indicative-past-tense>
		<indicative-present-continuous>
			<p><i>ging</i></p>
			<p><i>ging</i></p>
			<p><i>ging</i></p>
			<p><i>ging</i></p>
			<p><i>ging</i></p>
			<p><i>ging</i></p>
		</indicative-present-continuous>
		<indicative-present-perfect>
			<p><i>ged</i></p>
			<p><i>ged</i></p>
			<p><i>ged</i></p>
			<p><i>ged</i></p>
			<p><i>ged</i></p>
			<p><i>ged</i></p>
		</indicative-present-perfect>
	</indicative>
	<infinitive>
		<infinitive-present>
			<p><i></i></p>
		</infinitive-present>
	</infinitive>
	<imperative>
		<imperative-present>
			<p><i></i></p>
			<p><i></i></p>
			<p><i></i></p>
		</imperative-present>
	</imperative>
</template>

<template name="br:ing">
	<indicative>
		<indicative-present>
			<p><i>ing</i></p>
			<p><i>ing</i></p>
			<p><i>ings</i></p>
			<p><i>ing</i></p>
			<p><i>ing</i></p>
			<p><i>ing</i></p>
		</indicative-present>
		<indicative-past-tense>
			<p><i>ought</i></p>
			<p><i>ought</i></p>
			<p><i>ought</i></p>
			<p><i>ought</i></p>
			<p><i>ought</i></p>
			<p><i>ought</i></p>
		</indicative-past-tense>
		<indicative-present-continuous>
			<p><i>inging</i></p>
			<p><i>inging</i></p>
			<p><i>inging</i></p>
			<p><i>inging</i></p>
			<p><i>inging</i></p>
			<p><i>inging</i></p>
		</indicative-present-continuous>
		<indicative-present-perfect>
			<p><i>ought</i></p>
			<p><i>ought</i></p>
			<p><i>ought</i></p>
			<p><i>ought</i></p>
			<p><i>ought</i></p>
			<p><i>ought</i></p>
		</indicative-present-perfect>
	</indicative>
	<infinitive>
		<infinitive-present>
			<p><i>ing</i></p>
		</infinitive-present>
	</infinitive>
	<imperative>
		<imperative-present>
			<p><i>ing</i></p>
			<p><i>ing</i></p>
			<p><i>ing</i></p>
		</imperative-present>
	</imperative>
</template>

<template name="b:uy">
	<indicative>
		<indicative-present>
			<p><i>uy</i></p>
			<p><i>uy</i></p>
			<p><i>uys</i></p>
			<p><i>uy</i></p>
			<p><i>uy</i></p>
			<p><i>uy</i></p>
		</indicative-present>
		<indicative-past-tense>
			<p><i>ought</i></p>
			<p><i>ought</i></p>
			<p><i>ought</i></p>
			<p><i>ought</i></p>
			<p><i>ought</i></p>
			<p><i>ought</i></p>
		</indicative-past-tense>
		<indicative-present-continuous>
			<p><i>uying</i></p>
			<p><i>uying</i></p>
			<p><i>uying</i></p>
			<p><i>uying</i></p>
			<p><i>uying</i></p>
			<p><i>uying</i></p>
		</indicative-present-continuous>
		<indicative-present-perfect>
			<p><i>ought</i></p>
			<p><i>ought</i></p>
			<p><i>ought</i></p>
			<p><i>ought</i></p>
			<p><i>ought</i></p>
			<p><i>ought</i></p>
		</indicative-present-perfect>
	</indicative>
	<infinitive>
		<infinitive-present>
			<p><i>uy</i></p>
		</infinitive-present>
	</infinitive>
	<imperative>
		<imperative-present>
			<p><i>uy</i></p>
			<p><i>uy</i></p>
			<p><i>uy</i></p>
		</imperative-present>
	</imperative>
</template>

<template name="carr:y">
	<indicative>
		<indicative-present>
			<p><i>y</i></p>
			<p><i>y</i></p>
			<p><i>ies</i></p>
			<p><i>y</i></p>
			<p><i>y</i></p>
			<p><i>y</i></p>
		</indicative-present>
		<indicative-past-tense>
			<p><i>ied</i></p>
			<p><i>ied</i></p>
			<p><i>ied</i></p>
			<p><i>ied</i></p>
			<p><i>ied</i></p>
			<p><i>ied</i></p>
		</indicative-past-tense>
		<indicative-present-continuous>
			<p><i>ying</i></p>
			<p><i>ying</i></p>
			<p><i>ying</i></p>
			<p><i>ying</i></p>
			<p><i>ying</i></p>
			<p><i>ying</i></p>
		</indicative-present-continuous>
		<indicative-present-perfect>
			<p><i>ied</i></p>
			<p><i>ied</i></p>
			<p><i>ied</i></p>
			<p><i>ied</i></p>
			<p><i>ied</i></p>
			<p><i>ied</i></p>
		</indicative-present-perfect>
	</indicative>
	<infinitive>
		<infinitive-present>
			<p><i>y</i></p>
		</infinitive-present>
	</infinitive>
	<imperative>
		<imperative-present>
			<p><i>y</i></p>
			<p><i>y</i></p>
			<p><i>y</i></p>
		</imperative-present>
	</imperative>
</template>

<template name="ca:tch">
	<indicative>
		<indicative-present>
			<p><i>tch</i></p>
			<p><i>tch</i></p>
			<p><i>tches</i></p>
			<p><i>tch</i></p>
			<p><i>tch</i></p>
			<p><i>tch</i></p>
		</indicative-present>
		<indicative-past-tense>
			<p><i>ught</i></p>
			<p><i>ught</i></p>
			<p><i>ught</i></p>
			<p><i>ught</i></p>
			<p><i>ught</i></p>
			<p><i>ught</i></p>
		</indicative-past-tense>
		<indicative-present-continuous>
			<p><i>tching</i></p>
			<p><i>tching</i></p>
			<p><i>tching</i></p>
			<p><i>tching</i></p>
			<p><i>tching</i></p>
			<p><i>tching</i></p>
		</indicative-present-continuous>
		<indicative-present-perfect>
			<p><i>ught</i></p>
			<p><i>ught</i></p>
			<p><i>ught</i></p>
			<p><i>ught</i></p>
			<p><i>ught</i></p>
			<p><i>ught</i></p>
		</indicative-present-perfect>
	</indicative>
	<infinitive>
		<infinitive-present>
			<p><i>tch</i></p>
		</infinitive-present>
	</infinitive>
	<imperative>
		<imperative-present>
			<p><i>tch</i></p>
			<p><i>tch</i></p>
			<p><i>tch</i></p>
		</imperative-present>
	</imperative>
</template>

<template name="c:ome">
	<indicative>
		<indicative-present>
			<p><i>ome</i></p>
			<p><i>ome</i></p>
			<p><i>omes</i></p>
			<p><i>ome</i></p>
			<p><i>ome</i></p>
			<p><i>ome</i></p>
		</indicative-present>
		<indicative-past-tense>
			<p><i>ame</i></p>
			<p><i>ame</i></p>
			<p><i>ame</i></p>
			<p><i>ame</i></p>
			<p><i>ame</i></p>
			<p><i>ame</i></p>
		</indicative-past-tense>
		<indicative-present-continuous>
			<p><i>oming</i></p>
			<p><i>oming</i></p>
			<p><i>oming</i></p>
			<p><i>oming</i></p>
			<p><i>oming</i></p>
			<p><i>oming</i></p>
		</indicative-present-continuous>
		<indicative-present-perfect>
			<p><i>ome</i></p>
			<p><i>ome</i></p>
			<p><i>ome</i></p>
			<p><i>ome</i></p>
			<p><i>ome</i></p>
			<p><i>ome</i></p>
		</indicative-present-perfect>
	</indicative>
	<infinitive>
		<infinitive-present>
			<p><i>ome</i></p>
		</infinitive-present>
	</infinitive>
	<imperative>
		<imperative-present>
			<p><i>ome</i></p>
			<p><i>ome</i></p>
			<p><i>ome</i></p>
		</imperative-present>
	</imperative>
</template>

<template name="set:">
	<indicative>
		<indicative-present>
			<p><i></i></p>
			<p><i></i></p>
			<p><i>s</i></p>
			<p><i></i></p>
			<p><i></i></p>
			<p><i></i></p>
		</indicative-present>
		<indicative-past-tense>
			<p><i></i></p>
			<p><i></i></p>
			<p><i></i></p>
			<p><i></i></p>
			<p><i></i></p>
			<p><i></i></p>
		</indicative-past-tense>
		<indicative-present-continuous>
			<p><i>ting</i></p>
			<p><i>ting</i></p>
			<p><i>ting</i></p>
			<p><i>ting</i></p>
			<p><i>ting</i></p>
			<p><i>ting</i></p>
		</indicative-present-continuous>
		<indicative-present-perfect>
			<p><i></i></p>
			<p><i></i></p>
			<p><i></i></p>
			<p><i></i></p>
			<p><i></i></p>
			<p><i></i></p>
		</indicative-present-perfect>
	</indicative>
	<infinitive>
		<infinitive-present>
			<p><i></i></p>
		</infinitive-present>
	</infinitive>
	<imperative>
		<imperative-present>
			<p><i></i></p>
			<p><i></i></p>
			<p><i></i></p>
		</imperative-present>
	</imperative>
</template>

<template name="d:ie">
	<indicative>
		<indicative-present>
			<p><i>ie</i></p>
			<p><i>ie</i></p>
			<p><i>ies</i></p>
			<p><i>ie</i></p>
			<p><i>ie</i></p>
			<p><i>ie</i></p>
		</indicative-present>
		<indicative-past-tense>
			<p><i>ied</i></p>
			<p><i>ied</i></p>
			<p><i>ied</i></p>
			<p><i>ied</i></p>
			<p><i>ied</i></p>
			<p><i>ied</i></p>
		</indicative-past-tense>
		<indicative-present-continuous>
			<p><i>ying</i></p>
			<p><i>ying</i></p>
			<p><i>ying</i></p>
			<p><i>ying</i></p>
			<p><i>ying</i></p>
			<p><i>ying</i></p>
		</indicative-present-continuous>
		<indicative-present-perfect>
			<p><i>ied</i></p>
			<p><i>ied</i></p>
			<p><i>ied</i></p>
			<p><i>ied</i></p>
			<p><i>ied</i></p>
			<p><i>ied</i></p>
		</indicative-present-perfect>
	</indicative>
	<infinitive>
		<infinitive-present>
			<p><i>ie</i></p>
		</infinitive-present>
	</infinitive>
	<imperative>
		<imperative-present>
			<p><i>ie</i></p>
			<p><i>ie</i></p>
			<p><i>ie</i></p>
		</imperative-present>
	</imperative>
</template>

<template name="d:o">
	<indicative>
		<indicative-present>
			<p><i>o</i></p>
			<p><i>o</i></p>
			<p><i>oes</i></p>
			<p><i>o</i></p>
			<p><i>o</i></p>
			<p><i>o</i></p>
		</indicative-present>
		<indicative-past-tense>
			<p><i>id</i></p>
			<p><i>id</i></p>
			<p><i>id</i></p>
			<p><i>id</i></p>
			<p><i>id</i></p>
			<p><i>id</i></p>
		</indicative-past-tense>
		<indicative-present-continuous>
			<p><i>oing</i></p>
			<p><i>oing</i></p>
			<p><i>oing</i></p>
			<p><i>oing</i></p>
			<p><i>oing</i></p>
			<p><i>oing</i></p>
		</indicative-present-continuous>
		<indicative-present-perfect>
			<p><i>one</i></p>
			<p><i>one</i></p>
			<p><i>one</i></p>
			<p><i>one</i></p>
			<p><i>one</i></p>
			<p><i>one</i></p>
		</indicative-present-perfect>
	</indicative>
	<infinitive>
		<infinitive-present>
			<p><i>o</i></p>
		</infinitive-present>
	</infinitive>
	<imperative>
		<imperative-present>
			<p><i>o</i></p>
			<p><i>o</i></p>
			<p><i>o</i></p>
		</imperative-present>
	</imperative>
</template>

<template name="dr:ink">
	<indicative>
		<indicative-present>
			<p><i>ink</i></p>
			<p><i>ink</i></p>
			<p><i>inks</i></p>
			<p><i>ink</i></p>
			<p><i>ink</i></p>
			<p><i>ink</i></p>
		</indicative-present>
		<indicative-past-tense>
			<p><i>ank</i></p>
			<p><i>ank</i></p>
			<p><i>ank</i></p>
			<p><i>ank</i></p>
			<p><i>ank</i></p>
			<p><i>ank</i></p>
		</indicative-past-tense>
		<indicative-present-continuous>
			<p><i>inking</i></p>
			<p><i>inking</i></p>
			<p><i>inking</i></p>
			<p><i>inking</i></p>
			<p><i>inking</i></p>
			<p><i>inking</i></p>
		</indicative-present-continuous>
		<indicative-present-perfect>
			<p><i>unk</i></p>
			<p><i>unk</i></p>
			<p><i>unk</i></p>
			<p><i>unk</i></p>
			<p><i>unk</i></p>
			<p><i>unk</i></p>
		</indicative-present-perfect>
	</indicative>
	<infinitive>
		<infinitive-present>
			<p><i>ink</i></p>
		</infinitive-present>
	</infinitive>
	<imperative>
		<imperative-present>
			<p><i>ink</i></p>
			<p><i>ink</i></p>
			<p><i>ink</i></p>
		</imperative-present>
	</imperative>
</template>

<template name="dr:ive">
	<indicative>
		<indicative-present>
			<p><i>ive</i></p>
			<p><i>ive</i></p>
			<p><i>ives</i></p>
			<p><i>ive</i></p>
			<p><i>ive</i></p>
			<p><i>ive</i></p>
		</indicative-present>
		<indicative-past-tense>
			<p><i>ove</i></p>
			<p><i>ove</i></p>
			<p><i>ove</i></p>
			<p><i>ove</i></p>
			<p><i>ove</i></p>
			<p><i>ove</i></p>
		</indicative-past-tense>
		<indicative-present-continuous>
			<p><i>iving</i></p>
			<p><i>iving</i></p>
			<p><i>iving</i></p>
			<p><i>iving</i></p>
			<p><i>iving</i></p>
			<p><i>iving</i></p>
		</indicative-present-continuous>
		<indicative-present-perfect>
			<p><i>iven</i></p>
			<p><i>iven</i></p>
			<p><i>iven</i></p>
			<p><i>iven</i></p>
			<p><i>iven</i></p>
			<p><i>iven</i></p>
		</indicative-present-perfect>
	</indicative>
	<infinitive>
		<infinitive-present>
			<p><i>ive</i></p>
		</infinitive-present>
	</infinitive>
	<imperative>
		<imperative-present>
			<p><i>ive</i></p>
			<p><i>ive</i></p>
			<p><i>ive</i></p>
		</imperative-present>
	</imperative>
</template>

<template name=":eat">
	<indicative>
		<indicative-present>
			<p><i>eat</i></p>
			<p><i>eat</i></p>
			<p><i>eats</i></p>
			<p><i>eat</i></p>
			<p><i>eat</i></p>
			<p><i>eat</i></p>
		</indicative-present>
		<indicative-past-tense>
			<p><i>ate</i></p>
			<p><i>ate</i></p>
			<p><i>ate</i></p>
			<p><i>ate</i></p>
			<p><i>ate</i></p>
			<p><i>ate</i></p>
		</indicative-past-tense>
		<indicative-present-continuous>
			<p><i>eating</i></p>
			<p><i>eating</i></p>
			<p><i>eating</i></p>
			<p><i>eating</i></p>
			<p><i>eating</i></p>
			<p><i>eating</i></p>
		</indicative-present-continuous>
		<indicative-present-perfect>
			<p><i>eaten</i></p>
			<p><i>eaten</i></p>
			<p><i>eaten</i></p>
			<p><i>eaten</i></p>
			<p><i>eaten</i></p>
			<p><i>eaten</i></p>
		</indicative-present-perfect>
	</indicative>
	<infinitive>
		<infinitive-present>
			<p><i>eat</i></p>
		</infinitive-present>
	</infinitive>
	<imperative>
		<imperative-present>
			<p><i>eat</i></p>
			<p><i>eat</i></p>
			<p><i>eat</i></p>
		</imperative-present>
	</imperative>
</template>

<template name="f:all">
	<indicative>
		<indicative-present>
			<p><i>all</i></p>
			<p><i>all</i></p>
			<p><i>alls</i></p>
			<p><i>all</i></p>
			<p><i>all</i></p>
			<p><i>all</i></p>
		</indicative-present>
		<indicative-past-tense>
			<p><i>ell</i></p>
			<p><i>ell</i></p>
			<p><i>ell</i></p>
			<p><i>ell</i></p>
			<p><i>ell</i></p>
			<p><i>ell</i></p>
		</indicative-past-tense>
		<indicative-present-continuous>
			<p><i>alling</i></p>
			<p><i>alling</i></p>
			<p><i>alling</i></p>
			<p><i>alling</i></p>
			<p><i>alling</i></p>
			<p><i>alling</i></p>
		</indicative-present-continuous>
		<indicative-present-perfect>
			<p><i>allen</i></p>
			<p><i>allen</i></p>
			<p><i>allen</i></p>
			<p><i>allen</i></p>
			<p><i>allen</i></p>
			<p><i>allen</i></p>
		</indicative-present-perfect>
	</indicative>
	<infinitive>
		<infinitive-present>
			<p><i>all</i></p>
		</infinitive-present>
	</infinitive>
	<imperative>
		<imperative-present>
			<p><i>all</i></p>
			<p><i>all</i></p>
			<p><i>all</i></p>
		</imperative-present>
	</imperative>
</template>

<template name="fe:el">
	<indicative>
		<indicative-present>
			<p><i>el</i></p>
			<p><i>el</i></p>
			<p><i>els</i></p>
			<p><i>el</i></p>
			<p><i>el</i></p>
			<p><i>el</i></p>
		</indicative-present>
		<indicative-past-tense>
			<p><i>lt</i></p>
			<p><i>lt</i></p>
			<p><i>lt</i></p>
			<p><i>lt</i></p>
			<p><i>lt</i></p>
			<p><i>lt</i></p>
		</indicative-past-tense>
		<indicative-present-continuous>
			<p><i>eling</i></p>
			<p><i>eling</i></p>
			<p><i>eling</i></p>
			<p><i>eling</i></p>
			<p><i>eling</i></p>
			<p><i>eling</i></p>
		</indicative-present-continuous>
		<indicative-present-perfect>
			<p><i>lt</i></p>
			<p><i>lt</i></p>
			<p><i>lt</i></p>
			<p><i>lt</i></p>
			<p><i>lt</i></p>
			<p><i>lt</i></p>
		</indicative-present-perfect>
	</indicative>
	<infinitive>
		<infinitive-present>
			<p><i>el</i></p>
		</infinitive-present>
	</infinitive>
	<imperative>
		<imperative-present>
			<p><i>el</i></p>
			<p><i>el</i></p>
			<p><i>el</i></p>
		</imperative-present>
	</imperative>
</template>

<template name="f:ind">
	<indicative>
		<indicative-present>
			<p><i>ind</i></p>
			<p><i>ind</i></p>
			<p><i>inds</i></p>
			<p><i>ind</i></p>
			<p><i>ind</i></p>
			<p><i>ind</i></p>
		</indicative-present>
		<indicative-past-tense>
			<p><i>ound</i></p>
			<p><i>ound</i></p>
			<p><i>ound</i></p>
			<p><i>ound</i></p>
			<p><i>ound</i></p>
			<p><i>ound</i></p>
		</indicative-past-tense>
		<indicative-present-continuous>
			<p><i>inding</i></p>
			<p><i>inding</i></p>
			<p><i>inding</i></p>
			<p><i>inding</i></p>
			<p><i>inding</i></p>
			<p><i>inding</i></p>
		</indicative-present-continuous>
		<indicative-present-perfect>
			<p><i>ound</i></p>
			<p><i>ound</i></p>
			<p><i>ound</i></p>
			<p><i>ound</i></p>
			<p><i>ound</i></p>
			<p><i>ound</i></p>
		</indicative-present-perfect>
	</indicative>
	<infinitive>
		<infinitive-present>
			<p><i>ind</i></p>
		</infinitive-present>
	</infinitive>
	<imperative>
		<imperative-present>
			<p><i>ind</i></p>
			<p><i>ind</i></p>
			<p><i>ind</i></p>
		</imperative-present>
	</imperative>
</template>

<template name="fl:y">
	<indicative>
		<indicative-present>
			<p><i>y</i></p>
			<p><i>y</i></p>
			<p><i>ies</i></p>
			<p><i>y</i></p>
			<p><i>y</i></p>
			<p><i>y</i></p>
		</indicative-present>
		<indicative-past-tense>
			<p><i>ew</i></p>
			<p><i>ew</i></p>
			<p><i>ew</i></p>
			<p><i>ew</i></p>
			<p><i>ew</i></p>
			<p><i>ew</i></p>
		</indicative-past-tense>
		<indicative-present-continuous>
			<p><i>ying</i></p>
			<p><i>ying</i></p>
			<p><i>ying</i></p>
			<p><i>ying</i></p>
			<p><i>ying</i></p>
			<p><i>ying</i></p>
		</indicative-present-continuous>
		<indicative-present-perfect>
			<p><i>own</i></p>
			<p><i>own</i></p>
			<p><i>own</i></p>
			<p><i>own</i></p>
			<p><i>own</i></p>
			<p><i>own</i></p>
		</indicative-present-perfect>
	</indicative>
	<infinitive>
		<infinitive-present>
			<p><i>y</i></p>
		</infinitive-present>
	</infinitive>
	<imperative>
		<imperative-present>
			<p><i>y</i></p>
			<p><i>y</i></p>
			<p><i>y</i></p>
		</imperative-present>
	</imperative>
</template>

<template name="g:et">
	<indicative>
		<indicative-present>
			<p><i>et</i></p>
			<p><i>et</i></p>
			<p><i>ets</i></p>
			<p><i>et</i></p>
			<p><i>et</i></p>
			<p><i>et</i></p>
		</indicative-present>
		<indicative-past-tense>
			<p><i>ot</i></p>
			<p><i>ot</i></p>
			<p><i>ot</i></p>
			<p><i>ot</i></p>
			<p><i>ot</i></p>
			<p><i>ot</i></p>
		</indicative-past-tense>
		<indicative-present-continuous>
			<p><i>etting</i></p>
			<p><i>etting</i></p>
			<p><i>etting</i></p>
			<p><i>etting</i></p>
			<p><i>etting</i></p>
			<p><i>etting</i></p>
		</indicative-present-continuous>
		<indicative-present-perfect>
			<p><i>otten</i></p>
			<p><i>otten</i></p>
			<p><i>otten</i></p>
			<p><i>otten</i></p>
			<p><i>otten</i></p>
			<p><i>otten</i></p>
		</indicative-present-perfect>
	</indicative>
	<infinitive>
		<infinitive-present>
			<p><i>et</i></p>
		</infinitive-present>
	</infinitive>
	<imperative>
		<imperative-present>
			<p><i>et</i></p>
			<p><i>et</i></p>
			<p><i>et</i></p>
		</imperative-present>
	</imperative>
</template>

<template name="g:ive">
	<indicative>
		<indicative-present>
			<p><i>ive</i></p>
			<p><i>ive</i></p>
			<p><i>ives</i></p>
			<p><i>ive</i></p>
			<p><i>ive</i></p>
			<p><i>ive</i></p>
		</indicative-present>
		<indicative-past-tense>
			<p><i>ave</i></p>
			<p><i>ave</i></p>
			<p><i>ave</i></p>
			<p><i>ave</i></p>
			<p><i>ave</i></p>
			<p><i>ave</i></p>
		</indicative-past-tense>
		<indicative-present-continuous>
			<p><i>iving</i></p>
			<p><i>iving</i></p>
			<p><i>iving</i></p>
			<p><i>iving</i></p>
			<p><i>iving</i></p>
			<p><i>iving</i></p>
		</indicative-present-continuous>
		<indicative-present-perfect>
			<p><i>iven</i></p>
			<p><i>iven</i></p>
			<p><i>iven</i></p>
			<p><i>iven</i></p>
			<p><i>iven</i></p>
			<p><i>iven</i></p>
		</indicative-present-perfect>
	</indicative>
	<infinitive>
		<infinitive-present>
			<p><i>ive</i></p>
		</infinitive-present>
	</infinitive>
	<imperative>
		<imperative-present>
			<p><i>ive</i></p>
			<p><i>ive</i></p>
			<p><i>ive</i></p>
		</imperative-present>
	</imperative>
</template>

<template name=":go">
	<indicative>
		<indicative-present>
			<p><i>go</i></p>
			<p><i>go</i></p>
			<p><i>goes</i></p>
			<p><i>go</i></p>
			<p><i>go</i></p>
			<p><i>go</i></p>
		</indicative-present>
		<indicative-past-tense>
			<p><i>went</i></p>
			<p><i>went</i></p>
			<p><i>went</i></p>
			<p><i>went</i></p>
			<p><i>went</i></p>
			<p><i>went</i></p>
		</indicative-past-tense>
		<indicative-present-continuous>
			<p><i>going</i></p>
			<p><i>going</i></p>
			<p><i>going</i></p>
			<p><i>going</i></p>
			<p><i>going</i></p>
			<p><i>going</i></p>
		</indicative-present-continuous>
		<indicative-present-perfect>
			<p><i>gone</i></p>
			<p><i>gone</i></p>
			<p><i>gone</i></p>
			<p><i>gone</i></p>
			<p><i>gone</i></p>
			<p><i>gone</i></p>
		</indicative-present-perfect>
	</indicative>
	<infinitive>
		<infinitive-present>
			<p><i>go</i></p>
		</infinitive-present>
	</infinitive>
	<imperative>
		<imperative-present>
			<p><i>go</i></p>
			<p><i>go</i></p>
			<p><i>go</i></p>
		</imperative-present>
	</imperative>
</template>

<template name="ha:ve">
	<indicative>
		<indicative-present>
			<p><i>ve</i></p>
			<p><i>ve</i></p>
			<p><i>s</i></p>
			<p><i>ve</i></p>
			<p><i>ve</i></p>
			<p><i>ve</i></p>
		</indicative-present>
		<indicative-past-tense>
			<p><i>d</i></p>
			<p><i>d</i></p>
			<p><i>d</i></p>
			<p><i>d</i></p>
			<p><i>d</i></p>
			<p><i>d</i></p>
		</indicative-past-tense>
		<indicative-present-continuous>
			<p><i>ving</i></p>
			<p><i>ving</i></p>
			<p><i>ving</i></p>
			<p><i>ving</i></p>
			<p><i>ving</i></p>
			<p><i>ving</i></p>
		</indicative-present-continuous>
		<indicative-present-perfect>
			<p><i>d</i></p>
			<p><i>d</i></p>
			<p><i>d</i></p>
			<p><i>d</i></p>
			<p><i>d</i></p>
			<p><i>d</i></p>
		</indicative-present-perfect>
	</indicative>
	<infinitive>
		<infinitive-present>
			<p><i>ve</i></p>
		</infinitive-present>
	</infinitive>
	<imperative>
		<imperative-present>
			<p><i>ve</i></p>
			<p><i>ve</i></p>
			<p><i>ve</i></p>
		</imperative-present>
	</imperative>
</template>

<template name="hear:">
	<indicative>
		<indicative-present>
			<p><i></i></p>
			<p><i></i></p>
			<p><i>s</i></p>
			<p><i></i></p>
			<p><i></i></p>
			<p><i></i></p>
		</indicative-present>
		<indicative-past-tense>
			<p><i>d</i></p>
			<p><i>d</i></p>
			<p><i>d</i></p>
			<p><i>d</i></p>
			<p><i>d</i></p>
			<p><i>d</i></p>
		</indicative-past-tense>
		<indicative-present-continuous>
			<p><i>ing</i></p>
			<p><i>ing</i></p>
			<p><i>ing</i></p>
			<p><i>ing</i></p>
			<p><i>ing</i></p>
			<p><i>ing</i></p>
		</indicative-present-continuous>
		<indicative-present-perfect>
			<p><i>d</i></p>
			<p><i>d</i></p>
			<p><i>d</i></p>
			<p><i>d</i></p>
			<p><i>d</i></p>
			<p><i>d</i></p>
		</indicative-present-perfect>
	</indicative>
	<infinitive>
		<infinitive-present>
			<p><i></i></p>
		</infinitive-present>
	</infinitive>
	<imperative>
		<imperative-present>
			<p><i></i></p>
			<p><i></i></p>
			<p><i></i></p>
		</imperative-present>
	</imperative>
</template>

<template name="hid:e">
	<indicative>
		<indicative-present>
			<p><i>e</i></p>
			<p><i>e</i></p>
			<p><i>es</i></p>
			<p><i>e</i></p>
			<p><i>e</i></p>
			<p><i>e</i></p>
		</indicative-present>
		<indicative-past-tense>
			<p><i></i></p>
			<p><i></i></p>
			<p><i></i></p>
			<p><i></i></p>
			<p><i></i></p>
			<p><i></i></p>
		</indicative-past-tense>
		<indicative-present-continuous>
			<p><i>ing</i></p>
			<p><i>ing</i></p>
			<p><i>ing</i></p>
			<p><i>ing</i></p>
			<p><i>ing</i></p>
			<p><i>ing</i></p>
		</indicative-present-continuous>
		<indicative-present-perfect>
			<p><i>den</i></p>
			<p><i>den</i></p>
			<p><i>den</i></p>
			<p><i>den</i></p>
			<p><i>den</i></p>
			<p><i>den</i></p>
		</indicative-present-perfect>
	</indicative>
	<infinitive>
		<infinitive-present>
			<p><i>e</i></p>
		</infinitive-present>
	</infinitive>
	<imperative>
		<imperative-present>
			<p><i>e</i></p>
			<p><i>e</i></p>
			<p><i>e</i></p>
		</imperative-present>
	</imperative>
</template>

<template name="h:old">
	<indicative>
		<indicative-present>
			<p><i>old</i></p>
			<p><i>old</i></p>
			<p><i>olds</i></p>
			<p><i>old</i></p>
			<p><i>old</i></p>
			<p><i>old</i></p>
		</indicative-present>
		<indicative-past-tense>
			<p><i>eld</i></p>
			<p><i>eld</i></p>
			<p><i>eld</i></p>
			<p><i>eld</i></p>
			<p><i>eld</i></p>
			<p><i>eld</i></p>
		</indicative-past-tense>
		<indicative-present-continuous>
			<p><i>olding</i></p>
			<p><i>olding</i></p>
			<p><i>olding</i></p>
			<p><i>olding</i></p>
			<p><i>olding</i></p>
			<p><i>olding</i></p>
		</indicative-present-continuous>
		<indicative-present-perfect>
			<p><i>eld</i></p>
			<p><i>eld</i></p>
			<p><i>eld</i></p>
			<p><i>eld</i></p>
			<p><i>eld</i></p>
			<p><i>eld</i></p>
		</indicative-present-perfect>
	</indicative>
	<infinitive>
		<infinitive-present>
			<p><i>old</i></p>
		</infinitive-present>
	</infinitive>
	<imperative>
		<imperative-present>
			<p><i>old</i></p>
			<p><i>old</i></p>
			<p><i>old</i></p>
		</imperative-present>
	</imperative>
</template>

<template name="sle:ep">
	<indicative>
		<indicative-present>
			<p><i>ep</i></p>
			<p><i>ep</i></p>
			<p><i>eps</i></p>
			<p><i>ep</i></p>
			<p><i>ep</i></p>
			<p><i>ep</i></p>
		</indicative-present>
		<indicative-past-tense>
			<p><i>pt</i></p>
			<p><i>pt</i></p>
			<p><i>pt</i></p>
			<p><i>pt</i></p>
			<p><i>pt</i></p>
			<p><i>pt</i></p>
		</indicative-past-tense>
		<indicative-present-continuous>
			<p><i>eping</i></p>
			<p><i>eping</i></p>
			<p><i>eping</i></p>
			<p><i>eping</i></p>
			<p><i>eping</i></p>
			<p><i>eping</i></p>
		</indicative-present-continuous>
		<indicative-present-perfect>
			<p><i>pt</i></p>
			<p><i>pt</i></p>
			<p><i>pt</i></p>
			<p><i>pt</i></p>
			<p><i>pt</i></p>
			<p><i>pt</i></p>
		</indicative-present-perfect>
	</indicative>
	<infinitive>
		<infinitive-present>
			<p><i>ep</i></p>
		</infinitive-present>
	</infinitive>
	<imperative>
		<imperative-present>
			<p><i>ep</i></p>
			<p><i>ep</i></p>
			<p><i>ep</i></p>
		</imperative-present>
	</imperative>
</template>

<template name="kn:ow">
	<indicative>
		<indicative-present>
			<p><i>ow</i></p>
			<p><i>ow</i></p>
			<p><i>ows</i></p>
			<p><i>ow</i></p>
			<p><i>ow</i></p>
			<p><i>ow</i></p>
		</indicative-present>
		<indicative-past-tense>
			<p><i>ew</i></p>
			<p><i>ew</i></p>
			<p><i>ew</i></p>
			<p><i>ew</i></p>
			<p><i>ew</i></p>
			<p><i>ew</i></p>
		</indicative-past-tense>
		<indicative-present-continuous>
			<p><i>owing</i></p>
			<p><i>owing</i></p>
			<p><i>owing</i></p>
			<p><i>owing</i></p>
			<p><i>owing</i></p>
			<p><i>owing</i></p>
		</indicative-present-continuous>
		<indicative-present-perfect>
			<p><i>own</i></p>
			<p><i>own</i></p>
			<p><i>own</i></p>
			<p><i>own</i></p>
			<p><i>own</i></p>
			<p><i>own</i></p>
		</indicative-present-perfect>
	</indicative>
	<infinitive>
		<infinitive-present>
			<p><i>ow</i></p>
		</infinitive-present>
	</infinitive>
	<imperative>
		<imperative-present>
			<p><i>ow</i></p>
			<p><i>ow</i></p>
			<p><i>ow</i></p>
		</imperative-present>
	</imperative>
</template>

<template name="sa:y">
	<indicative>
		<indicative-present>
			<p><i>y</i></p>
			<p><i>y</i></p>
			<p><i>ys</i></p>
			<p><i>y</i></p>
			<p><i>y</i></p>
			<p><i>y</i></p>
		</indicative-present>
		<indicative-past-tense>
			<p><i>id</i></p>
			<p><i>id</i></p>
			<p><i>id</i></p>
			<p><i>id</i></p>
			<p><i>id</i></p>
			<p><i>id</i></p>
		</indicative-past-tense>